
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Service
{

using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    

public partial interface ICategoryService : Data.Service.IBaseService<Category>
{
}

public partial class CategoryService : Data.Service.BaseService<Category>, ICategoryService
{
    public CategoryService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.ICategoryRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
