
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Service
{

using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    

public partial interface ICustomerService : Data.Service.IBaseService<Customer>
{
}

public partial class CustomerService : Data.Service.BaseService<Customer>, ICustomerService
{
    public CustomerService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.ICustomerRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
