
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Service
{

using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    

public partial interface IDishService : Data.Service.IBaseService<Dish>
{
}

public partial class DishService : Data.Service.BaseService<Dish>, IDishService
{
    public DishService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.IDishRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
