
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Service
{

using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    

public partial interface IOrderDishService : Data.Service.IBaseService<OrderDish>
{
}

public partial class OrderDishService : Data.Service.BaseService<OrderDish>, IOrderDishService
{
    public OrderDishService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.IOrderDishRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
