
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Service
{

using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    

public partial interface IOrderService : Data.Service.IBaseService<Order>
{
}

public partial class OrderService : Data.Service.BaseService<Order>, IOrderService
{
    public OrderService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.IOrderRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
