
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Service
{

using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    

public partial interface IPromotionService : Data.Service.IBaseService<Promotion>
{
}

public partial class PromotionService : Data.Service.BaseService<Promotion>, IPromotionService
{
    public PromotionService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.IPromotionRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
