
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Service
{

using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    

public partial interface ISubCategoryService : Data.Service.IBaseService<SubCategory>
{
}

public partial class SubCategoryService : Data.Service.BaseService<SubCategory>, ISubCategoryService
{
    public SubCategoryService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.ISubCategoryRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
