
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Service
{

using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    

public partial interface ITableService : Data.Service.IBaseService<Table>
{
}

public partial class TableService : Data.Service.BaseService<Table>, ITableService
{
    public TableService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.ITableRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
