//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        [StringLength(60, ErrorMessage = "Số kí tự tối đa là 60")]
        [Required(ErrorMessage = "Chưa nhập tên")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Chưa nhập giới tính")]
        public Nullable<int> Sex { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "chưa nhập ngày sinh")]
        public Nullable<System.DateTime> Birthday { get; set; }
        [StringLength(12, ErrorMessage = "Số kí tự tối đa là 12")]
        [Required(ErrorMessage = "Chưa nhập SĐT")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Chưa nhập địa chỉ")]
        public string Address { get; set; }
        [Range(0,2,ErrorMessage = "Loại khách hàng không phù hợp")]
        public int Class { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
