//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int ID { get; set; }
        [StringLength(60, ErrorMessage = "Số kí tự tối đa là 60")]
        [Required(ErrorMessage = "Chưa nhập tên")]
        public string Name { get; set; }
        [Required(ErrorMessage = "chưa nhập bộ phận")]
        public string Department { get; set; }
        [Required(ErrorMessage = "chưa nhập vị trí")]
        public string Position { get; set; }
        [Range(0, 2, ErrorMessage = "Sex chưa phù hợp")]
        [Required(ErrorMessage = "Chưa nhập giới tính")]
        public int Sex { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "chưa nhập ngày sinh")]
        public Nullable<System.DateTime> Birthday { get; set; }
        [StringLength(12, ErrorMessage = "Số kí tự tối đa là 12")]
        [Required(ErrorMessage = "Chưa nhập SĐT")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Chưa nhập địa chỉ")]
        public string Address { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Avatar { get; set; }
        public string UserId { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
    }
}
