//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderDish
    {
        public int Id { get; set; }
        [Range(1, 10000, ErrorMessage ="Số lượng chưa phù hợp")]
        [Required(ErrorMessage = "Chưa nhập số lượng")]
        public int Quantity { get; set; }
        public long UnitPrice { get; set; }
        public Nullable<long> Discount { get; set; }
        public int DishID { get; set; }
        public int OrderID { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Order Order { get; set; }
    }
}
