//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotion()
        {
            this.OrderDishes = new HashSet<OrderDish>();
        }
    
        public int Id { get; set; }
        public double DiscountPercent { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateAt { get; set; }
        public System.DateTime ExpireAt { get; set; }
        public Nullable<int> DishID { get; set; }
    
        public virtual Dish Dish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDish> OrderDishes { get; set; }
    }
}
