//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        [StringLength(60, ErrorMessage = "Số kí tự tối đa là 60")]
        [Required(ErrorMessage = "Chưa nhập mã bàn")]
        public string Code { get; set; }
        [StringLength(60, ErrorMessage = "Số kí tự tối đa là 60")]
        [Required(ErrorMessage = "Chưa nhập chú thích")]
        public string Description { get; set; }
        [Range(0, 2, ErrorMessage ="tình trạng chưa phù hợp")]
        [Required(ErrorMessage = "Chưa chọn tình trạng bàn")]
        public int Status { get; set; }
        public Nullable<int> GroupTableID { get; set; }
    
        public virtual GroupTable GroupTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
