
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Model.ViewModels
{

using System;
    using System.Collections.Generic;
    
public partial class DishViewModel
{
	
	
		public virtual int ID { get; set; }
	
		public virtual string Name { get; set; }
	
		public virtual string Description { get; set; }
	
		public virtual bool IsDelete { get; set; }
	
		public virtual string Image { get; set; }
	
		public virtual long Price { get; set; }
	
		public virtual int OrderTimes { get; set; }
	
		public virtual int SubCategoryID { get; set; }
	
}

}
