
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Model.ViewModels
{

using System;
    using System.Collections.Generic;
    
public partial class EmployeeViewModel
{
	
	
		public virtual int ID { get; set; }
	
		public virtual string Name { get; set; }
	
		public virtual string Department { get; set; }
	
		public virtual string Position { get; set; }
	
		public virtual int Sex { get; set; }
	
		public virtual Nullable<System.DateTime> Birthday { get; set; }
	
		public virtual string Phone { get; set; }
	
		public virtual string Address { get; set; }
	
		public virtual Nullable<System.DateTime> CreatedAt { get; set; }
	
		public virtual Nullable<bool> IsDelete { get; set; }
	
		public virtual string Avatar { get; set; }
	
		public virtual string UserId { get; set; }
	
}

}
