
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Model.ViewModels
{

using System;
    using System.Collections.Generic;
    
public partial class OrderViewModel
{
	
	
		public virtual int Id { get; set; }
	
		public virtual System.DateTime CreateAt { get; set; }
	
		public virtual bool IsDelete { get; set; }
	
		public virtual long SubTotal { get; set; }
	
		public virtual Nullable<long> PromotionDiscount { get; set; }
	
		public virtual Nullable<long> ClassDiscount { get; set; }
	
		public virtual Nullable<long> Total { get; set; }
	
		public virtual Nullable<int> Status { get; set; }
	
		public virtual Nullable<int> CustomerID { get; set; }
	
		public virtual int EmployeeID { get; set; }
	
		public virtual int TableID { get; set; }
	
}

}
