
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Model.ViewModels
{

using System;
    using System.Collections.Generic;
    
public partial class OrderDishViewModel
{
	
	
		public virtual int Id { get; set; }
	
		public virtual string Description { get; set; }
	
		public virtual int Number { get; set; }
	
		public virtual long UnitPrice { get; set; }
	
		public virtual bool IsDelete { get; set; }
	
		public virtual Nullable<long> Discount { get; set; }
	
		public virtual Nullable<int> PromotionID { get; set; }
	
		public virtual int DishID { get; set; }
	
		public virtual int OrderID { get; set; }
	
}

}
