
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Model.ViewModels
{

using System;
    using System.Collections.Generic;
    
public partial class PromotionViewModel
{
	
	
		public virtual int Id { get; set; }
	
		public virtual double DiscountPercent { get; set; }
	
		public virtual string Name { get; set; }
	
		public virtual string Description { get; set; }
	
		public virtual System.DateTime CreateAt { get; set; }
	
		public virtual System.DateTime ExpireAt { get; set; }
	
		public virtual Nullable<int> DishID { get; set; }
	
}

}
