
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Model.ViewModels
{

using System;
    using System.Collections.Generic;
    
public partial class TableViewModel
{
	
	
		public virtual int Id { get; set; }
	
		public virtual string Code { get; set; }
	
		public virtual string Description { get; set; }
	
		public virtual int Status { get; set; }
	
		public virtual Nullable<int> GroupTableID { get; set; }
	
}

}
