
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Repository
{

using System;
    using System.Collections.Generic;
    using Model.Entities;
    

public partial interface ICustomerRepository : Data.Repository.IBaseRepository<Customer>
{
}

public partial class CustomerRepository : Data.Repository.BaseRepository<Customer>, ICustomerRepository
{
	public CustomerRepository(Entities dbContext) : base(dbContext)
    {
    }
}

}
