
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Repository
{

using System;
    using System.Collections.Generic;
    using Model.Entities;
    

public partial interface IDishRepository : Data.Repository.IBaseRepository<Dish>
{
}

public partial class DishRepository : Data.Repository.BaseRepository<Dish>, IDishRepository
{
	public DishRepository(Entities dbContext) : base(dbContext)
    {
    }
}

}
